### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by ycarissan** [pierredesaxce/WebAromaticityGenerator#2]
Tout est dans le titre

12:32 $ python3 main.py 
main.py:134: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig, ax = plt.subplots(1, 2, figsize=(10, 5), dpi=80)
WARNING: QApplication was not created in the main() thread.
['12']
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 99, in interface_create_projection
    canvas = FigureCanvasTkAgg(create_projection(filename), master=graph_frame)
  File "main.py", line 173, in create_projection
    list_aroma[-1].append(float(cur_line[0]))
IndexError: list index out of range

**Comment by pierredesaxce** [comment]
Le lien pour cloner le repo donné dans le read.me était incorrect et menait à un autre projet. Il est maintenant corrigé et pointe bien vers ce repo.
