### ISSUE TITLE
Probleme a la soumission

### ISSUE THREAD

**Issue by ycarissan** [pierredesaxce/WebAromaticityGenerator#4]
IndexError: list index out of range
127.0.0.1 - - [30/Jun/2022 12:45:01] "POST /confirmation HTTP/1.1" 500 -
127.0.0.1 - - [30/Jun/2022 12:45:04] "GET / HTTP/1.1" 200 -
         O            0.611390115614    -0.000006716468    -0.000000000000

         C           -0.613209884386    -0.000006716468    -0.000000000000

         H           -1.200909884386     0.242593283532    -0.899800000000

         H           -1.200909884386    -0.242406716468     0.899800000000

[2022-06-30 12:45:09,564] ERROR in app: Exception on /confirmation [POST]
Traceback (most recent call last):
  File "/home/yannick/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yannick/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yannick/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yannick/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "server.py", line 168, in confirm
    job_id = ((stdout.readlines())[-1].split())[-1]
IndexError: list index out of range
127.0.0.1 - - [30/Jun/2022 12:45:09] "POST /confirmation HTTP/1.1" 500 -

**Comment by pierredesaxce** [comment]
J'aurais besoin du fichier utilisé afin d'essayer d'identifier ce qui est arrivé.

**Comment by pierredesaxce** [comment]
Probleme resolu
